[TH2-366] Correct the README file
th2-net/th2-codec pull request #3
Opened 2020-11-23 17:18 UTC by OptimumOpium

The information about codec configuration, implementations loading and pins definition was corrected

2020-11-26 12:14 UTC, jean-michel-perli-sonsin requested changes

2020-11-26 12:14 UTC, jean-michel-perli-sonsin commented on README.md
> +Their should be defined in the `custom-config` section of the component configuration.
**They** should be defined in the `custom-config` section of the component configuration.

2020-11-26 12:14 UTC, jean-michel-perli-sonsin commented on README.md
> +A codec might not have any parameters to configure. In that case, you can omit adding those parameters.
**It's possible** that a codec might not have any parameters to configure. In **this** case, you can omit adding those parameters.

2020-11-26 12:14 UTC, jean-michel-perli-sonsin commented on README.md
> +The set of parameters depends on the codec implementation is used.
The set of parameters depends on the codec implementation **that** is used.

2020-11-26 12:14 UTC, jean-michel-perli-sonsin commented on README.md
> +The first one is used to receive messages to decode/encode. The second one - to send decoded/encoded messages further.
The first one is used to receive messages to decode/encode **while the** second one **is used** to send decoded/encoded messages further.

2020-11-26 12:14 UTC, jean-michel-perli-sonsin commented on README.md
>  For example, you have got big source data stream, and you want to split them on some pins via session alias.
For example, you **got** a big source data stream, and you want to split them **into** some pins via session alias.

2020-11-26 12:14 UTC, jean-michel-perli-sonsin commented on README.md
> +The filtering can also be performed for pins with  `subscribe` attribute.
The filtering can also be **applied** for pins with `subscribe` attribute.

2020-11-26 14:21 UTC, OptimumOpium commented on README.md
> +Both types of pins can have filters, depending on which the input / output of the encoder / decoder can be partially or completely filtered out.
I would try to say that the input and output for decoders and encoders might be filtered depending on the filters each pin has.

Will the following option be correct?
> Both types of pins may have filters. The input / output of the encoder and decoder can be partially or entirely filtered out depending on filters the pin has.

2020-11-26 14:30 UTC, jean-michel-perli-sonsin commented on README.md
> +Both types of pins can have filters, depending on which the input / output of the encoder / decoder can be partially or completely filtered out.
The following option is correct and does not change the semantic. I would just add a "which" before the word filters (depending on which filters...), the rest of the sentence is right.

2020-11-26 14:51 UTC, jean-michel-perli-sonsin requested changes
Please refer to the previous comments that I made after the topic "running", the other points corrected are ok now.

2020-11-26 15:29 UTC, OptimumOpium commented on README.md
> +Codec has four types of connection: stream and general for encode and decode functions.
Why `have`? `Codec` is not a plural form. I think that
> Codec has ...

is the correct option

2020-11-26 15:37 UTC, OptimumOpium commented
@jean-michel-perli-sonsin Please, approve the merge if everything is ok in your opinion

2020-11-26 15:47 UTC, jean-michel-perli-sonsin requested changes

2020-11-26 15:47 UTC, jean-michel-perli-sonsin commented on README.md
> +Codec has four types of connection: stream and general for encode and decode functions.
"Has" is used with the pronouns he, she, it and with singular nouns. So in this case, the codec has is correct.

2020-11-30 09:09 UTC, OptimumOpium commented
@jean-michel-perli-sonsin As far as I can see, all change requests were resolved. Could you please approve the merge is everything is ok?

2020-11-30 09:45 UTC, jean-michel-perli-sonsin requested changes

2020-11-30 09:45 UTC, jean-michel-perli-sonsin commented on README.md
> +The codec loads all JAR files from that directory and looks for all implementations of
The codec loads all JAR files from that directory and looks for all **the** implementations of

2020-11-30 09:51 UTC, Nikita-Smirnov-Exactpro approved these changes

2020-11-30 10:28 UTC, merged